# Permalinks
permalink:           pretty

# Setup
title:               lewisrodgers.com
tagline:             Cloud enthusiast
url:                 http://lewisrodgers.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lewis Rodgers
  email:             contact@lewisrodgers.com
  bio:               Cloud architect and data engineer, IoT hobbyist, big fan of machine learning.
  twitter:           https://twitter.com/lewisrodgers
  linkedin:          https://www.linkedin.com/in/lewisrodgers/

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/lewisrodgers/lewisrodgers.github.io
analytics_id:        UA-64548447-1

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.md